language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk14

script: mvn clean jacoco:prepare-agent install jacoco:report

after_success:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh)
