language: java
jdk:
  -openjdk14

jobs:
  include:
    - stage: test
      script: ./gradlew test ; ./gradlew pitest ; ./gradlew jacocoTestReport
      
after_success:
  -  bash <(curl -Ls https://coverage.codacy.com/get.sh)
